/*
   main.c
   Copyright (C) 2007, 2008  Stanislav Bohm

   This file is part of Kreatrix.

   Kreatrix is free software; you can redistribute it and/or modify it under
   the terms of the GNU General Public License as published by the Free
   Software Foundation; either version 2, or (at your option) any later
   version.

   Kreatrix is distributed in the hope that it will be useful, 
   but WITHOUT ANY WARRANTY; without even the implied warranty 
   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Kreatrix; see the file COPYING. If not, see 
   <http://www.gnu.org/licenses/>.
*/
	

#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include "../../compiler/kxcompiler.h"

void print_help() {
	printf("kx2carray - Kreatrix to C Array\n");
	printf("Compile .kx file and bytecode saved as C Array.\n");
	printf("Last parameter is name of array\n\n");
	printf("Usage: kx2carray <input_file> <output_file> <arrayname>\n");
}

int save_as_c_array(FILE *file ,char *bytecode, int size, char *array_name) 
{
	fprintf(file, "\n\nchar %s[%i] = {\n", array_name, size);

	int t;
	for (t=0;t<size-1;t++) {
		fprintf(file,"%3i,", bytecode[t]);
		if ((t+1) % 10 == 0)
			fprintf(file,"\n");
		else
			fprintf(file," ");
	}
	if (size)
		fprintf(file,"%3i", bytecode[size-1]);
	fprintf(file,"\n};\n");
}

int main(int argc, char **argv) 
{
	if (argc < 4) {
		print_help();
		return -1;
	}

	char *bytecode;
	int bytecode_size;
	
	List *errors = kxc_compile_file(argv[1], 0, 2, &bytecode, &bytecode_size);
	
	if (errors != NULL) {
		int t;
		for (t=0;t<errors->size;t++)
			printf("%s\n", errors->items[t]);
		list_free_all(errors);
		return -1;
	}
	
	FILE *fileout = fopen(argv[2],"w");
	if (!fileout) {
		fprintf(stderr,"Can't open file '%s': %s", argv[2],strerror(errno));
		return 0;
	}

	fprintf(fileout,
		"\n/*\n * Generated by kx2carray from file '%s'.\n */", argv[1]);

	if (!save_as_c_array(fileout, bytecode, bytecode_size, argv[3])) {
		fclose(fileout);
		free(bytecode);
		return -1;
	}

	fclose(fileout);
	free(bytecode);
	return 0;
}
