
#ifndef __KXINSTR_H
#define __KXINSTR_H

typedef enum { 	
	
	KXCI_UNARY_MSG,  // 0
	KXCI_BINARY_MSG, 
	KXCI_KEYWORD_MSG,
	KXCI_LOCAL_UNARY_MSG,
	KXCI_LOCAL_KEYWORD_MSG, // 4
	KXCI_RESEND_UNARY_MSG,
	KXCI_RESEND_KEYWORD_MSG,

	KXCI_PUSH_INTEGER, // 7
	KXCI_PUSH_STRING,
	KXCI_PUSH_FLOAT,
	KXCI_PUSH_SYMBOL, // 10
	KXCI_PUSH_CHARACTER, // 11

	KXCI_POP, // 12

	KXCI_PUSH_METHOD, // 13
	KXCI_PUSH_BLOCK,
	KXCI_LIST,
	KXCI_END_OF_BLOCK,
	KXCI_RETURN,
	KXCI_RETURNSELF, // 18
	KXCI_LONGRETURN, // 19

	KXCI_PUSH_LOCAL0 = 32,
	KXCI_PUSH_LOCAL1,
	KXCI_PUSH_LOCAL2,
	KXCI_PUSH_LOCAL3,
	KXCI_PUSH_LOCAL4,
	KXCI_PUSH_LOCAL5,
	KXCI_PUSH_LOCAL6,
	KXCI_PUSH_LOCAL7,
	KXCI_PUSH_LOCALN,

	KXCI_PUSH_SELF,
	KXCI_PUSH_ACTIVATION,

	KXCI_UPDATE_LOCAL0,
	KXCI_UPDATE_LOCAL1,
	KXCI_UPDATE_LOCAL2,
	KXCI_UPDATE_LOCAL3,
	KXCI_UPDATE_LOCAL4,
	KXCI_UPDATE_LOCAL5,
	KXCI_UPDATE_LOCAL6,
	KXCI_UPDATE_LOCAL7,
	KXCI_UPDATE_LOCALN,

	KXCI_INSTRUCTIONS_COUNT
} KxInstructionType;


#endif
