
#ifndef __KXINSTR_H
#define __KXINSTR_H

typedef enum { 	
	
	KXCI_UNARY_MSG,  // 0
	KXCI_BINARY_MSG, 
	KXCI_KEYWORD_MSG,
	KXCI_LOCAL_UNARY_MSG,
	KXCI_LOCAL_KEYWORD_MSG, // 4
	KXCI_RESEND_UNARY_MSG,
	KXCI_RESEND_KEYWORD_MSG,

	KXCI_PUSH_LITERAL0, // 7
	KXCI_PUSH_LITERAL1,
	KXCI_PUSH_LITERAL2,
	KXCI_PUSH_LITERAL3,
	KXCI_PUSH_LITERAL4,
	KXCI_PUSH_LITERAL5,
	KXCI_PUSH_LITERAL6,
	KXCI_PUSH_LITERALN,

	KXCI_POP, // 15

	KXCI_PUSH_METHOD, // 16
	KXCI_PUSH_BLOCK,
	KXCI_LIST,
	KXCI_END_OF_BLOCK,
	KXCI_RETURN,
	KXCI_RETURNSELF, // 21
	KXCI_LONGRETURN, // 22

	KXCI_PUSH_LOCAL0 = 32,
	KXCI_PUSH_LOCAL1,
	KXCI_PUSH_LOCAL2,
	KXCI_PUSH_LOCAL3,
	KXCI_PUSH_LOCAL4,
	KXCI_PUSH_LOCAL5,
	KXCI_PUSH_LOCAL6,
	KXCI_PUSH_LOCAL7,
	KXCI_PUSH_LOCALN, // 40
	KXCI_PUSH_OUTER_LOCAL, // 51

	KXCI_PUSH_SELF,   // 42
	KXCI_PUSH_ACTIVATION, // 43

	KXCI_UPDATE_LOCAL0, // 44
	KXCI_UPDATE_LOCAL1,
	KXCI_UPDATE_LOCAL2,
	KXCI_UPDATE_LOCAL3,
	KXCI_UPDATE_LOCAL4,
	KXCI_UPDATE_LOCAL5,
	KXCI_UPDATE_LOCAL6,
	KXCI_UPDATE_LOCAL7,
	KXCI_UPDATE_LOCALN,
	KXCI_UPDATE_OUTER_LOCAL, // 54

	KXCI_INSTRUCTIONS_COUNT
} KxInstructionType;

typedef enum {
	KXC_LITERAL_SYMBOL,
	KXC_LITERAL_INTEGER,
	KXC_LITERAL_FLOAT,
	KXC_LITERAL_STRING,
	KXC_LITERAL_CHAR
} KxcLiteralType;


#endif
