
#ifndef __KXINSTR_H
#define __KXINSTR_H

typedef enum { 	
	
	KXCI_UNARY_MSG,  // 0
	KXCI_BINARY_MSG, 
	KXCI_KEYWORD_MSG,
	KXCI_LOCAL_UNARY_MSG,
	KXCI_LOCAL_KEYWORD_MSG, // 4
	KXCI_RESEND_UNARY_MSG,
	KXCI_RESEND_KEYWORD_MSG,

	KXCI_PUSH_INTEGER, // 7
	KXCI_PUSH_STRING,
	KXCI_PUSH_FLOAT,
	KXCI_PUSH_SYMBOL, // 10
	KXCI_PUSH_CHARACTER, // 11

	KXCI_POP, // 12

	KXCI_PUSH_METHOD, // 13
	KXCI_PUSH_BLOCK,
	KXCI_LIST,
	KXCI_END_OF_BLOCK,
	KXCI_RETURN,
	KXCI_RETURNSELF, // 18
	KXCI_LONGRETURN, // 19

	KXCI_INSTRUCTIONS_COUNT
} KxInstructionType;


#endif
