/**********************************************
 *
 *  This file is generated by kxgtk generator
 *
 **********************************************/

#ifndef __KX_GTK_WRAPPER_H
#define __KX_GTK_WRAPPER_H

#include <gtk/gtk.h>

#include "kxobject_struct.h"
#include "kxcore.h"


