/**********************************************
 *
 *  This file is generated by kxgtk generator
 *
 **********************************************/


#include <stdlib.h>
#include <string.h>

#include "kxmessage.h"
#include "kxobject.h"
#include "kxcfunction.h"
#include "kxinteger.h"
#include "kxfloat.h"
#include "kxstring.h"
#include "kxexception.h"
#include "gdkevent.h"
#include "kxgtk_wrapper.h"
#include "gtk_utils.h"

