/**
 *   Generated by wrapgen
 */ 

#include <stdlib.h>

%include%

#include <kreatrix/kxmessage.h>
#include <kreatrix/kxobject.h>
#include <kreatrix/kxcfunction.h>
#include <kreatrix/kxinteger.h>
#include <kreatrix/kxstring.h>

static void
kx%name%_add_method_table(KxObject *self);

KxObject *
kx%name%_new(KxCore *core)
{
	KxObject *self = kxcore_clone_base_object(core);
	
%init_prototype% 
	
	kx%name%_add_method_table(self);

	return self;
}


%cfunctions%

static void
kx%name%_add_method_table(KxObject *self)
{
	KxMethodTable table[] = {
%cfunctions_table%
		{NULL,0, NULL}
	};
	kxobject_add_methods(self, table);
}
