/**
 *   Generated by wrapgen
 */ 

#include <stdlib.h>

%include%

#include <kreatrix/kxmessage.h>
#include <kreatrix/kxobject.h>
#include <kreatrix/kxcfunction.h>
#include <kreatrix/kxinteger.h>
#include <kreatrix/kxstring.h>
#include <kreatrix/kxexception.h>

#include "%name%.h"

KxObjectExtension kx%name%_extension;

static void
kx%name%_add_method_table(Kx%Name% *self);

KxObject *
kx%name%_new_prototype(KxCore *core)
{
	KxObject *self = kxcore_clone_base_object(core);
	self->extension = &kx%name%_extension;
	
%init_prototype% 
	
	kx%name%_add_method_table(self);

	return self;
}

KxObject *
kx%name%_new_from(KxCore *core, %data% data)
{
	KxObject *proto = kxcore_get_prototype(core, &kx%name%_extension);
	KxObject *self = kxobject_raw_clone(proto);

	//%new_from%
	self->data.ptr = data;

	return self;
}

%cfunctions%

void kx%name%_extension_init() {
	kxobjectext_init(&kx%name%_extension);
	kx%name%_extension.type_name = "%Name%";

%init_extension%
}


static void
kx%name%_add_method_table(KxObject *self)
{
	KxMethodTable table[] = {
%cfunctions_table%
		{NULL,0, NULL}
	};
	kxobject_add_methods(self, table);
}
